check again ssh conn

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -39,9 +39,12 @@ jobs:
           # Read simulated user input from file
           option=$(cat selected_option.txt)
           echo "Selected option: $option"
-
-      - name: Deploy to server
-        run: |
-          # Replace with direct deployment commands after SSH login
-          ssh -o StrictHostKeyChecking=no -p 3022 8551@gate.jpc.infomaniak.com "mkdir -p /home/jelastic/ROOT"
-           echo "3" | scp -o StrictHostKeyChecking=no -P 3022 -r client/build 8551@gate.jpc.infomaniak.com:/home/jelastic/ROOT
+          # Depending on the selected option, you can execute corresponding commands
+          if [ "$option" = "3" ]; then
+            ssh -o StrictHostKeyChecking=no -p 3022 8551@gate.jpc.infomaniak.com "mkdir -p /home/jelastic/ROOT"
+            scp -o StrictHostKeyChecking=no -P 3022 -r client/build 8551@gate.jpc.infomaniak.com:/home/jelastic/ROOT
+          else
+            echo "Invalid option selected."
+            exit 1
+          fi
+                                                                                                                                                     
