check again ssh conn

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -34,17 +34,35 @@ jobs:
       - name: Simulate User Input
         run: echo "3" > selected_option.txt
 
+      - name: Read Selected Option
+        id: read_option
+        run: |
+          option=$(cat selected_option.txt)
+          echo "::set-output name=selected_option::$option"
+
       - name: Select Environment
         run: |
-          # Read simulated user input from file
-          option=$(cat selected_option.txt)
-          echo "Selected option: $option"
-          # Depending on the selected option, you can execute corresponding commands
-          if [ "$option" = "3" ]; then
-            ssh -o StrictHostKeyChecking=no -p 3022 8551@gate.jpc.infomaniak.com "mkdir -p /home/jelastic/ROOT"
-            scp -o StrictHostKeyChecking=no -P 3022 -r client/build 8551@gate.jpc.infomaniak.com:/home/jelastic/ROOT
-          else
-            echo "Invalid option selected."
-            exit 1
-          fi
-                                                                                                                                                     
+          selected_option=${{ steps.read_option.outputs.selected_option }}
+          case $selected_option in
+            0)
+              echo "Exiting deployment process."
+              exit 0
+              ;;
+            1)
+              echo "Refreshing environment list."
+              # Add commands to refresh environment list if needed
+              ;;
+            2)
+              echo "Performing actions for [My First Project] [0]:(0)."
+              # Add commands specific to [My First Project] [0]:(0) environment
+              ;;
+            3)
+              echo "Performing actions for env-5868270.jcloud.ik-server.com."
+              ssh -o StrictHostKeyChecking=no -p 3022 8551@gate.jpc.infomaniak.com "mkdir -p /home/jelastic/ROOT"
+              scp -o StrictHostKeyChecking=no -P 3022 -r client/build 8551@gate.jpc.infomaniak.com:/home/jelastic/ROOT
+              ;;
+            *)
+              echo "Invalid option selected."
+              exit 1
+              ;;
+          esac
